{
 "title": "Database Controller Metrics",
 "description": "Database controller monitoring dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "DB Claims custom metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total number of DB claims",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dbcontroller_total_database_claims{app_kubernetes_io_instance=\"db-controller\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DBClaims using existing source (true/false)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (use_existing_source) (dbcontroller_existing_source_claims{app_kubernetes_io_instance=\"db-controller\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB claims with ready db state",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dbcontroller_active_db_state{db_state=\"ready\", app_kubernetes_io_instance=\"db-controller\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB claims in error state",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(env) (dbcontroller_error_state_claims{app_kubernetes_io_instance=\"db-controller\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Reconciliation Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Reconciliation Rate",
   "type": "timeseries",
   "description": "Calculates the total rate of reconciliations per minute for the databaseclaim controller.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{controller=\"databaseclaim\"}[1m])) * 60",
     "legendFormat": "reconciliations per minute"
    }
   ]
  },
  {
   "title": "Reconciliation Duration",
   "type": "timeseries",
   "description": "Displays the 95th percentile of reconciliation duration for the databaseclaim controller over a 5-minute window.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(controller_runtime_reconcile_time_seconds_bucket[1m])) by (le))",
     "legendFormat": "95th percentile of reconciliation duration"
    }
   ]
  },
  {
   "title": "Reconciliation Success Rate",
   "type": "timeseries",
   "description": "Calculates the percentage of successful reconciliations over the total number of reconciliations for the databaseclaim controller.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{controller=\"databaseclaim\", result=\"success\"}[1m])) * 60",
     "legendFormat": "rate of successful reconciliations over the last minute"
    }
   ]
  },
  {
   "title": "Reconciliation Errors",
   "type": "timeseries",
   "description": "Calculates the total rate of reconciliation errors per minute for the databaseclaim controller.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_errors_total{controller=\"databaseclaim\"}[1m])) * 60",
     "legendFormat": "total rate of reconciliation errors per minute"
    }
   ]
  },
  { "title": "Work Queue Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Work Queue Depth",
   "type": "stat",
   "description": "Shows the current depth of the work queue for the databaseclaim controller.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(workqueue_depth)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Work Queue Latency",
   "type": "timeseries",
   "description": "Displays the 95th percentile of time items spend in the work queue for the databaseclaim controller.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(workqueue_queue_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "95th percentile of time items spend in the work queue"
    }
   ]
  },
  {
   "title": "Work Queue Processing Duration",
   "type": "timeseries",
   "description": "Displays the 95th percentile of time taken to process items in the work queue for the databaseclaim controller.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(workqueue_work_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "95th percentile of time taken to process items in the work queue"
    }
   ]
  },
  {
   "title": "Longest Work Queue Waiting Time",
   "type": "timeseries",
   "description": "Shows the maximum time that any item has been waiting in the work queue for the databaseclaim controller.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(workqueue_longest_running_processor_seconds)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Work Queue Retries",
   "type": "timeseries",
   "description": "Calculates the rate of work queue retries per minute for the databaseclaim controller.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_retries_total{name=\"databaseclaim\"}[1m])) * 60",
     "legendFormat": "rate of work queue retries per minute"
    }
   ]
  },
  { "title": "Computation Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Avg CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total[2m]))",
     "legendFormat": "Avg CPU"
    }
   ]
  },
  {
   "title": "Avg Memory usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(process_resident_memory_bytes)",
     "legendFormat": "Avg Memory"
    }
   ]
  },
  {
   "title": "Databases",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Databases Created",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum(databases_created_total)", "legendFormat": "Total Databases Created" }
     ]
    },
    {
     "title": "Active Database Claims",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_customresource{kind=\"DatabaseClaim\"})",
       "legendFormat": "Active Database Claims"
      },
      {},
      {}
     ]
    },
    {
     "title": "Database Creation Errors",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(database_creation_errors_total)",
       "legendFormat": "Creation Errors"
      }
     ]
    }
   ]
  },
  {
   "title": "Password rotation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Passwords rotated total",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(password_rotated_total[$__range])"
      }
     ]
    },
    {
     "title": "Avg password rotation time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 3, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(password_rotation_time_seconds_sum[24h]) / increase(password_rotation_time_seconds_count[24h])\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Password rotation errors rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 14, "x": 9, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(password_rotation_time_seconds_bucket[5m])) by (reason)"
      }
     ]
    }
   ]
  }
 ]
}