# permissions for end users to edit dbroleclaims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: dbroleclaim-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: db-controller
    app.kubernetes.io/part-of: db-controller
    app.kubernetes.io/managed-by: kustomize
  name: dbroleclaim-editor-role
rules:
- apiGroups:
  - persistance.atlas.infoblox.com
  resources:
  - dbroleclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - persistance.atlas.infoblox.com
  resources:
  - dbroleclaims/status
  verbs:
  - get
