# permissions for end users to view dbroleclaims.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: migration
    app.kubernetes.io/managed-by: kustomize
  name: dbroleclaim-viewer-role
rules:
- apiGroups:
  - persistance.atlas.infoblox.com
  resources:
  - dbroleclaims
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - persistance.atlas.infoblox.com
  resources:
  - dbroleclaims/status
  verbs:
  - get
