apiVersion: persistance.atlas.infoblox.com/v1
kind: DatabaseClaim
metadata:
  labels:
    app.kubernetes.io/name: migration
    app.kubernetes.io/managed-by: kustomize
  name: databaseclaim-sample
spec:
  # TODO(user): Add fields here
