apiVersion: persistance.atlas.infoblox.com/v1
kind: DatabaseClaim
metadata:
  name: databaseclaim-sample
  namespace: {{ .Release.Namespace }}
spec:
  app_id: sample-app
  secret_name: sample-secret
  type: postgres
  instance_label: sample-connection
  user_name: sample_user
  database_name: sample_app
