apiVersion: v1
kind: Secret
metadata:
  name: alloydb-psc-test-creds
  namespace: dwells
type: Opaque
data:
  password: bXlwYXNzd29yZA== # mypassword
---
apiVersion: persistance.infoblox.com/v1alpha1
kind: XNetworkRecord
metadata:
  name: alloydb-psc-network
  annotations:
    crossplane.io/external-name: alloydb-psc-network
spec:
  parameters:
    pscDNSName: ''
    serviceAttachmentLink: ''
    region: us-east1
    subnetwork: projects/gcp-eng-ddiaas-dev/regions/us-east1/subnetworks/private-service-connect
    network: projects/gcp-eng-ddiaas-dev/global/networks/ddiaas-dev-use1-vpc
---
apiVersion: alloydb.gcp.upbound.io/v1beta2
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: alloydb/v1beta1/instance
  labels:
    testing.upbound.io/example-name: alloydb-psc-test
  name: alloydb-psc-test
spec:
  providerConfigRef:
    name: default
  # writeConnectionSecretToRef:
  #   name: alloydb-creds-cluster
  #   namespace: dwells
  # Doesn't appear to work
  # publishConnectionDetailsTo:
  #   name: publish-alloydb-creds-cluster
  forProvider:
    initialUser:
      passwordSecretRef:
        key: password
        name: alloydb-psc-test-creds
        namespace: dwells
      user: postgres
    location: us-east1
    networkConfig:
    pscConfig:
      pscEnabled: true
---
apiVersion: alloydb.gcp.upbound.io/v1beta2
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: alloydb/v1beta2/instance
  labels:
    testing.upbound.io/alloydbinstance: alloydb-psc-test
  name: alloydb-psc-test
spec:
  providerConfigRef:
    name: default
  # writeConnectionSecretToRef:
  #   name: alloydb-creds-instance
  #   namespace: dwells
  forProvider:
    clusterSelector:
      matchLabels:
        testing.upbound.io/example-name: alloydb-psc-test
    # How to set this to basic? https://cloud.google.com/alloydb/docs/overview?authuser=3#instances
    databaseFlags:
      "alloydb.iam_authentication": "on"
    instanceType: PRIMARY
    machineConfig:
      cpuCount: 2
    pscInstanceConfig:
      allowedConsumerProjects:
        - gcp-eng-ddiaas-dev
  # publishConnectionDetailsTo:
  #   name: publish-alloydb-creds-instance
---
