apiVersion: persistance.atlas.infoblox.com/v1
kind: DatabaseClaim
metadata:
  name: databaseclaim-sample
  namespace: dbclaim-sample
spec:
  appId: sample-app
  class: default
  databaseName: sample_app
  dbVersion: ''
  dsnName: sample-postgres-dsn
  enableReplicationRole: false
  enableSuperUser: false
  instanceLabel: ''
  host: localhost
  port: '5432'
  minStorageGB: 2
  secretName: databaseclaim-sample
  shape: db.t4g.medium
  type: postgres
  useExistingSource: true
  userName: sample_user
  sourceDataFrom:
    #s3 or database
    type: database
    #Database defines the connection information to an existing db
    database:
      dsn: ''
      secretRef:
        namespace: ''
        name: ''
    #S3 defines the location of a DB backup in an S3 bucket
    s3:
      region: ''
      #+required
      bucket: ''
      #Prefix is the path prefix of the S3 bucket within which the backup to restore is located.
      prefix: ''
      #SourceEngine is the engine used to create the backup.
      sourceEngine: mysql # mysql or postgres
      #SourceEngineVersion is the version of the engine used to create the backup.
      #Example: "5.7.30"
      sourceEngineVersion: ''
      #SecretRef specifies a secret to use for connecting to the s3 bucket via AWS client
      #TODO: document/validate the secret format required
      #+optional
      secretRef:
        namespace: ''
        name: ''
  #  The 30-minute maintenance window is selected at random from an 8-hour block of time per region.
  #  If you don't specify a maintenance window when you create the DB cluster, RDS assigns a 30-minute
  #  maintenance window on a randomly selected day of the week.
  #  Uncomment the field below to specify a value.
  #  preferredMaintenanceWindow: 03:00-03:30