apiVersion: persistance.atlas.infoblox.com/v1
kind: DatabaseClaim
metadata:
  name: databaseclaim-sample
  namespace: dbclaim-sample
spec:
  appId: sample-app
  class: default
  databaseName: sample_app
  dbVersion: ''
  dsnName: sample-postgres-dsn
  enableReplicationRole: false
  enableSuperUser: false
  instanceLabel: sample-connection
  minStorageGB: 0
  secretName: databaseclaim-sample
  shape: ''
  type: postgres
  useExistingSource: false
  userName: sample_user
#  The 30-minute maintenance window is selected at random from an 8-hour block of time per region.
#  If you don't specify a maintenance window when you create the DB cluster, RDS assigns a 30-minute
#  maintenance window on a randomly selected day of the week.
#  Uncomment the field below to specify a value.
#  preferredMaintenanceWindow: 03:00-03:30
