apiVersion: persistance.atlas.infoblox.com/v1
kind: DbRoleClaim
metadata:
  annotations:
    meta.helm.sh/release-name: dbclaim-sample
    meta.helm.sh/release-namespace: dbclaim-sample
  creationTimestamp: "2024-06-14T00:20:10Z"
  finalizers:
  - dbroleclaims.persistance.atlas.infoblox.com/finalizer
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
    helm.toolkit.fluxcd.io/name: dbclaim-sample
    helm.toolkit.fluxcd.io/namespace: vela-system
  name: roleclaim-new-user-schema-role
  namespace: dbclaim-sample
  resourceVersion: "1425628477"
  uid: 413c7405-9993-4827-a2df-c308ccc8b4a5
spec:
  class: default
  sourceDatabaseClaim:
    namespace: dbclaim-sample
    name: databaseclaim-sample
  secretName: sample-master-secret
  schemarolemap:
    public: admin
    schema1: regular
    schema2: admin
    schema3: readonly
    schema4: admin