apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Name }}-{{ .Release }}
  namespace: {{ .Namespace }}
  ownerReferences:
    - apiVersion: persistance.atlas.infoblox.com/v1
      blockOwnerDeletion: true
      controller: true
      kind: DatabaseClaim
      name: {{ .Name }}
      uid: {{ .DBClaimOwnerRef }}
  labels:
    app: {{ .Name }}
    release: {{ .Release }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Name }}
      release: {{ .Release }}
  template:
    metadata:
      labels:
        app: {{ .Name }}
        release: {{ .Release }}
{{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | trim | indent 8 }}
{{- end }}
      annotations:
        checksum/config: {{ .ConfigCheckSum }}
{{- if .Values.annotations }}
{{- toYaml .Values.annotations | nindent 8 }}
{{- end }}
    spec:
      serviceAccountName: {{ .ServiceAccountName }}
    {{- if .ImagePullSecrets }}
      imagePullSecrets:
      {{- range .ImagePullSecrets }}
        - name: {{ . }}
      {{- end }}
    {{- end }}
      containers:
        - name: {{ .Name }}
          args:
          - "--extend.query-path=/etc/config.yaml"
          {{- if .Values.config.disableDefaultMetrics }}
          - "--disable-default-metrics"
          {{- end }}
          {{- if .Values.config.disableSettingsMetrics }}
          - "--disable-settings-metrics"
          {{- end }}
          {{- if .Values.config.autoDiscoverDatabases }}
          - "--auto-discover-databases"
          {{- if .Values.config.excludeDatabases }}
          - "--exclude-databases"
          - {{ .Values.config.excludeDatabases | join "," }}
          {{- end }}
          {{- if .Values.config.includeDatabases }}
          - "--include-databases"
          - {{ .Values.config.includeDatabases | join "," }}
          {{- end }}
          {{- end }}
          {{- if .Values.config.constantLabels }}
          {{ $firstLabel := true -}}
          - "--constantLabels={{- range $k, $v := .Values.config.constantLabels }}{{- if not $firstLabel -}},{{ end -}}{{ $firstLabel = false -}}{{ $k }}={{ $v }}{{- end }}"
          {{- end }}
          {{- if .Values.config.logLevel }}
          - "--log.level={{ .Values.config.logLevel }}"
          {{- end}}
          {{- if .Values.config.logFormat }}
          - "--log.format={{ .Values.config.logFormat }}"
          {{- end}}
          env:
          - name: DATA_SOURCE_NAME
            valueFrom:
              secretKeyRef:
                name: "{{ .DatasourceSecretName }}"
                key: {{ .DatasourceFileName }}
          - name: DATA_SOURCE_USER
            value: {{ .DatasourceUser }}
          image: "{{ .ImageRepo }}:{{ .ImageTag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9187
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - sh
              - -c
              - wget -q -O - http://localhost:9187/metrics | grep '^pg_up ' | awk '{if ($2 == 1) exit 0; else exit 1;}'
            failureThreshold: 3
            initialDelaySeconds: 300
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            initialDelaySeconds: 0
            timeoutSeconds: 1
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Resources | indent 12 }}
          volumeMounts:
            - name: queries
              mountPath: /etc/config.yaml
              subPath: config.yaml
{{- with .Values.extraContainers }}
{{ toYaml . | indent 8 }}
{{- end }}
      securityContext:
{{ toYaml .Values.securityContext | indent 8 }}
{{- if .Values.hostAliases }}
      hostAliases:
{{ toYaml .Values.hostAliases | indent 8 }}
{{- end }}
     {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
      - configMap:
          defaultMode: 420
          {{- if not .Values.config.externalQueries.enabled }}
          name: {{ .Name }}-{{.Release }}
          {{- else }}
          name: {{ .Values.config.externalQueries.configmap }}
          {{- end }}
        name: queries
{{- with .Values.extraVolumes }}
{{ toYaml . | indent 6 }}
{{- end }}
