apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "db-controller.name" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  {{- with .Values.controllerConfig }}
  {{- tpl (toYaml . | trim | nindent 2 ) $ }}
  {{ end }}
