apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "db-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "db-controller.labels" . | nindent 4 }}
data:
  {{- (.Files.Glob "files/*.yaml").AsConfig | nindent 2 }}
