{{- if or ( .Values.dbproxy.enabled ) ( .Values.dsnexec.enabled ) }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "db-controller.fullname" . }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "db-controller.fullname" . }}-webhook
webhooks:
{{- if .Values.dbproxy.enabled }}
- clientConfig:
    service:
      name: {{ include "db-controller.fullname" . }}
      path: /mutate--v1-pod
      port: 9443
      namespace: {{ .Release.Namespace }}
  sideEffects: None
  admissionReviewVersions: ["v1"]
  failurePolicy: Fail
  name: persistance.atlas.infoblox.com
  objectSelector:
    matchExpressions:
      - key: "persistance.atlas.infoblox.com/databaseclaim"
        operator: "Exists"
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
    scope: "Namespaced"
{{- end }}
{{- if .Values.dsnexec.enabled }}
- clientConfig:
    service:
      name: {{ include "db-controller.fullname" . }}
      path: /mutate-dsnexec
      port: 9443
      namespace: {{ .Release.Namespace }}
  sideEffects: None
  admissionReviewVersions: ["v1"]
  failurePolicy: Ignore
  name: dsnexec-injector.infoblox.com
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
    scope: "Namespaced"
{{- end }}
{{- end }}
