{{ if .Values.pdb.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "db-controller.name" . }}-pdb
spec:
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "db-controller.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}
