apiVersion: v1
kind: Service
metadata:
  name: {{ include "db-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "db-controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
    - port: 9443
      protocol: TCP
      targetPort: webhook
      name: dbproxy-webhook
  selector:
    {{- include "db-controller.selectorLabels" . | nindent 4 }}
