{{ $appName := include "db-controller.fullname" . }}
{{ $namespace := .Release.Namespace }}
{{- $ctx := . }}
{{- if .Values.space.enabled }}
{{- range $key, $secretRef := .Values.passwordSecretRefs }}
apiVersion: spacecontroller.infoblox-cto.github.com/v1alpha1
kind: Space
metadata:
  name: {{ lower $key }}
  namespace: {{ $namespace }}
  labels:
    app.kubernetes.io/name: {{ include "db-controller.name" $ctx }}
    helm.sh/chart: {{ include "db-controller.chart" $ctx }}
    app.kubernetes.io/instance: {{ $namespace }}
    app.kubernetes.io/managed-by: {{ $namespace }}
spec:
  secretName: {{ lower $key }}
  {{- range $refKey, $refValue := $secretRef }}
  {{- if eq $refKey "secrets" }}
  {{ $refKey }}:
  {{- range $skey, $svalue := $refValue }}
    {{ $skey }}: {{ tpl $svalue $ctx }}
  {{- end }}
    {{- else }}
  {{ $refKey }}: {{ tpl $refValue $ctx }}
  {{- end }}
  {{- end }}
---
  {{- end }}
{{- end }}
