{{- if .Values.dbproxy.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "db-controller.fullname" . }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "db-controller.fullname" . }}
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: {{ include "db-controller.fullname" . }}
      path: /mutate
      port: 7443
      namespace: {{ .Release.Namespace }}
  sideEffects: None
  admissionReviewVersions: ["v1"]
  failurePolicy: Ignore
  name: dbproxy-injector.infoblox.com
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
    scope: "Namespaced"
{{- end }}
