configs:
  # this is an example config to use the shelldb driver

  # this is an example config to use the fprintf driver
  # it will write json of the sources to a file
  filewrite:
    sources:
    - driver: postgres
      filename: test/source.pg.dsn
    destination:
      driver: fprintf
      # The $tmp variable is a special variable that is the path to a temporary directory
      # The hostname endcodes the rendering driver. fmt.Fprintf is the default driver
      # which can be specificed by 'fprintf' 
      dsn: file:////Users/bjeevan/git/github.com/Infobloxopen/db-controller/dsnexec/myfile.json
    commands:
    - command: "%s" # commands can have text/templates also
                    # this is the format string for the fprintf driver
      args:
      # these are arguments to the fmt.Fprintf function
      - '{{ index . "test/source.pg.json" }}'
      # - '{{ . }}'

