{{- if .Values.secrets.enabled }}
{{ $namespace := .Release.Namespace }}
{{- $ctx := . }}
  {{- $release := .Release }}
  {{- range $key, $secret := .Values.passwordSecretRefs }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ lower $key }}
  namespace: {{ $namespace }}
  labels:
    app.kubernetes.io/name: {{ include "db-controller.name" $ctx }}
    helm.sh/chart: {{ include "db-controller.chart" $ctx }}
    app.kubernetes.io/instance: {{ $release.Name }}
    app.kubernetes.io/managed-by: {{ $release.Service }}
type: Opaque
stringData:
    {{- range $skey, $svalue := $secret }}
      {{ $skey }}: {{ tpl $svalue $ctx }}
    {{- end }}
---
{{- end }}
{{- end }}
