apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-hooks
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "db-controller-crds.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: "pre-install,pre-upgrade"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-hooks
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "db-controller-crds.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: "pre-install,pre-upgrade"
rules:
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - "customresourcedefinitions/status"
    verbs:
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-hooks
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "db-controller-crds.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: "pre-install,pre-upgrade"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-hooks
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-hooks
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-pre
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "db-controller-crds.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: "pre-install,pre-upgrade"
spec:
  serviceAccountName: {{ .Release.Name }}-hooks
  containers:
    - name: wait
      image: {{ .Values.tools.kubectl.repository }}:{{ .Values.tools.kubectl.tag }}
      command:
        - /bin/bash
        - -cxe
        - |
          # Tell Flux not to delete the CRDs
          # https://fluxcd.io/flux/components/kustomize/kustomizations/#prune
          kubectl label crd
          {{- include "db-controller-crds.getCRDNames" . }} 'kustomize.toolkit.fluxcd.io/prune=disabled'
          # Tell Helm not to delete the CRDs
          # https://helm.sh/docs/howto/charts_tips_and_tricks/#tell-helm-not-to-uninstall-a-resource
          kubectl annotate crd
          {{- include "db-controller-crds.getCRDNames" . }} 'helm.sh/resource-policy=keep'
  restartPolicy: Never
---
